vim.opt.runtimepath:prepend(vim.fn.getcwd())
vim.cmd.runtime('plugin/fujutsu.lua')
local dir = vim.fn.tempname()
vim.fn.mkdir(dir, 'p')
local function jj(args)
  local r = vim.system(vim.list_extend({ 'jj', '--no-pager', '--color=never' }, args), { cwd = dir, text = true }):wait()
  assert(r.code == 0, r.stderr)
  return vim.trim(r.stdout)
end
local function id(rev, template) return jj({ 'log', '--no-graph', '-r', rev, '-T', template or 'commit_id' }) end
jj({ 'git', 'init' })
jj({ 'config', 'set', '--repo', 'user.name', 'Test' })
jj({ 'config', 'set', '--repo', 'user.email', 'test@example.com' })
jj({ 'describe', '-m', 'base' })
vim.fn.writefile({ 'base' }, dir .. '/file')
jj({ 'bookmark', 'create', 'base' })
jj({ 'new', '-m', 'child' })
jj({ 'bookmark', 'create', 'child' })
vim.cmd.cd(dir)
vim.cmd([[J log -r 'all()']])
local buf = vim.api.nvim_get_current_buf()
local log = require('fujutsu').log(buf)
local function focus(rev)
  vim.api.nvim_set_current_buf(buf); log.refresh(buf)
  local commit = id(rev)
  for i, row in pairs(log.rows) do
    if row.id == commit and row.first == i then vim.api.nvim_win_set_cursor(0, { i, 0 }); return end
  end
  error('Missing commit')
end
local function create(key, rev)
  focus(rev)
  local job = require('fujutsu.actions').create(log, buf, dir, require('fujutsu.selection').capture(log, false), key)
  assert(vim.wait(10000, function() return job.result ~= nil end, 20))
  assert(job.result.code == 0, job.result.stderr)
end
create('gn', 'base')
assert(id('parents(@)') == id('base'))
assert(id('parents(child)') == id('@'))
assert(vim.api.nvim_get_current_buf() == buf, 'Creation should focus the log, not open a description')
local rendered = table.concat(vim.api.nvim_buf_get_lines(buf, 0, -1, false), '\n')
assert(rendered:find('(empty)', 1, true) and rendered:find('(no description set)', 1, true),
  'Native default-template indicators must be preserved')
local wc = id('@', 'change_id')
create('gN', 'base')
assert(id('@', 'change_id') == wc)
assert(id('parents(parents(base))') == id('root()'))
create('ge', 'child')
assert(id('@') == id('child'))
-- Native history includes external operations, and marking does not disturb redo.
local description = id('@', 'description')
jj({ 'describe', '-m', 'external operation' })
local function history(command)
  local job = require('fujutsu.actions').history(dir, command)
  assert(vim.wait(10000, function() return job.result ~= nil end, 20))
  assert(job.result.code == 0, job.result.stderr)
end
history('undo'); assert(id('@', 'description') == description)
log.refresh(buf)
require('fujutsu.marks').modify('a', 'replace', { id('@', 'change_id') }, log.catalog)
history('redo'); assert(id('@', 'description') == 'external operation')
history('undo'); history('undo')
assert(id('@') ~= id('child'))
history('redo'); assert(id('@') == id('child'))
print('PASS: native undo/redo includes external operations and skips UI-only mark changes')
-- Guard real unsaved buffers before a working-copy switch.
vim.cmd.edit(dir .. '/file')
vim.api.nvim_buf_set_lines(0, 0, -1, false, { 'unsaved' })
local ok = pcall(require('fujutsu.runner').guard, dir)
assert(not ok)
vim.bo.modified = false
print('PASS: creation stays in log, parent insertion preserves @, ge and unsaved-buffer guard')
vim.cmd.cd('/')
vim.fn.delete(dir, 'rf')
vim.cmd.qa({ bang = true })
