vim.opt.runtimepath:prepend(vim.fn.getcwd())
vim.cmd.runtime('plugin/fujutsu.lua')
local file = require('fujutsu.file')
local root = vim.fn.tempname()
vim.fn.mkdir(root, 'p')
root = vim.uv.fs_realpath(root)
local function jj(args) return file.jj(root, args) end
local function eq(a, b) assert(vim.deep_equal(a, b), vim.inspect({ expected = a, actual = b })) end
local function test()
  jj({ 'git', 'init' })
  vim.fn.writefile({ 'one', 'two', 'three' }, root .. '/file.lua')
  jj({ 'describe', '-m', 'base' })
  local base = file.resolve(root, '@')
  jj({ 'new' })
  vim.fn.writefile({ 'one', 'changed', 'three' }, root .. '/file.lua')
  local current = file.resolve(root, '@')
  eq('one\ntwo\nthree\n', file.base(root, current, 'file.lua'))
  file.open(root, base, 'file.lua')
  eq(true, vim.bo.readonly); eq(true, vim.bo.modifiable); eq('lua', vim.bo.filetype)
  eq(base, vim.b.fujutsu_file.id)
  file.open(root, current, 'file.lua', { workspace = true })
  local workspace = vim.api.nvim_get_current_buf()
  file.open(root, current, 'file.lua', { workspace = true })
  eq(workspace, vim.api.nvim_get_current_buf())
  local log = require('fujutsu.log').new(root, file.jj)
  local buf = vim.api.nvim_create_buf(false, true)
  vim.api.nvim_set_current_buf(buf)
  log.refresh(buf)
  local function find(predicate)
    for i, row in pairs(log.rows) do if predicate(row) then return i end end
    error('row not found')
  end
  vim.api.nvim_win_set_cursor(0, { find(function(r) return r.path == 'file.lua' end), 0 })
  log.toggle(buf)
  local removed = find(function(r) return r.old_side end)
  vim.api.nvim_win_set_cursor(0, { removed, 0 }); log.visit(buf)
  eq(base, vim.b.fujutsu_file.id); eq(2, vim.fn.line('.'))
  vim.api.nvim_set_current_buf(buf)
  vim.api.nvim_win_set_cursor(0, { find(function(r) return r.new_line == 2 and not r.old_side and not r.hunk end), 0 })
  log.visit(buf); eq(workspace, vim.api.nvim_get_current_buf()); eq(2, vim.fn.line('.'))
  print('PASS: revision snapshots, merged-base extraction, workspace reuse, and diff coordinates')
  file.open(root, base, 'file.lua')
  local historical = vim.api.nvim_get_current_buf()
  vim.api.nvim_buf_set_lines(0, 0, -1, false, { 'saved', 'two', 'three' })
  eq(false, pcall(file.write, historical, {}))
  vim.bo.readonly = false
  vim.cmd('Jwrite --restore-descendants')
  eq(false, vim.bo.modified)
  eq('saved\ntwo\nthree\n', file.content(root, vim.b.fujutsu_file.id, 'file.lua'))
  eq('one\nchanged\nthree\n', file.content(root, '@', 'file.lua'))
  local saved = vim.b.fujutsu_file.id
  jj({ 'describe', '-r', saved, '-m', 'description only' })
  vim.cmd.write()
  local meta = vim.b.fujutsu_file
  jj({ 'restore', '--from', '@', '--to', meta.id, 'file.lua' })
  vim.api.nvim_buf_set_lines(0, 0, -1, false, { 'replacement' })
  eq(false, pcall(file.write, historical, {})); eq(true, vim.bo.modified)
  vim.bo[workspace].modified = true
  eq(false, pcall(file.write, historical, { bang = true }))
  vim.bo[workspace].modified = false
  vim.cmd('Jwrite! --restore-descendants')
  eq('replacement\n', file.content(root, vim.b.fujutsu_file.id, 'file.lua'))
  eq(false, pcall(vim.cmd, 'Jwrite --ignore-imm'))
  print('PASS: readonly, diffedit writes, descendant restoration, stale and unsaved-buffer guards')
  vim.cmd.cd(root)
  vim.cmd('Jedit')
  eq(workspace, vim.api.nvim_get_current_buf()); eq(false, vim.bo.readonly)
  vim.cmd('Jview -r ' .. base)
  eq(base, vim.b.fujutsu_file.id); eq(true, vim.bo.readonly); eq(true, vim.bo.modifiable)
  vim.cmd('Jedit -r ' .. base)
  eq(false, vim.bo.readonly)
  vim.api.nvim_buf_set_lines(0, 0, -1, false, { 'unsaved' })
  vim.cmd('only!') -- No other window can keep this modified buffer alive.
  vim.o.hidden = false
  eq(false, pcall(vim.cmd, 'Jedit'))
  vim.o.hidden = true
  vim.cmd('Jedit')
  vim.fn.writefile({ 'dash' }, root .. '/-dash name.lua')
  vim.cmd('Jview -- -dash\\ name.lua')
  eq(root .. '/-dash name.lua', vim.api.nvim_buf_get_name(0)); eq(true, vim.bo.readonly)
  eq(false, pcall(vim.cmd, 'Jedit --unknown'))
  assert(vim.tbl_contains(require('fujutsu.commands').complete('@', 'Jedit -r @'), '@'))
  print('PASS: Jedit/Jview defaults, historical identity, literal paths, completion, and hidden safeguards')
  vim.cmd('Jedit file.lua')
  local before = #vim.api.nvim_tabpage_list_wins(0)
  vim.cmd('Jsplit -r ' .. base)
  eq(before + 1, #vim.api.nvim_tabpage_list_wins(0)); eq(false, vim.bo.readonly)
  local splitwin = vim.api.nvim_get_current_win()
  vim.cmd('Jvsplit -r ' .. base)
  assert(vim.api.nvim_win_get_width(0) < vim.o.columns); eq(base, vim.b.fujutsu_file.id)
  local tabs = #vim.api.nvim_list_tabpages()
  vim.cmd('Jtabedit file.lua'); eq(tabs + 1, #vim.api.nvim_list_tabpages())
  local origin = vim.api.nvim_get_current_win()
  vim.cmd('Jpedit -r ' .. base .. ' file.lua')
  eq(origin, vim.api.nvim_get_current_win())
  local preview
  for _, win in ipairs(vim.api.nvim_tabpage_list_wins(0)) do
    if vim.wo[win].previewwindow then preview = win end
  end
  assert(preview); eq(base, vim.b[vim.api.nvim_win_get_buf(preview)].fujutsu_file.id)
  vim.cmd('Jpedit file.lua')
  eq(2, #vim.api.nvim_tabpage_list_wins(0)); eq(workspace, vim.api.nvim_win_get_buf(preview))
  vim.api.nvim_set_current_win(splitwin)
  local count = #vim.api.nvim_tabpage_list_wins(0)
  vim.cmd('Jdrop -r ' .. base .. ' file.lua')
  eq(count, #vim.api.nvim_tabpage_list_wins(0)); eq(base, vim.b.fujutsu_file.id)
  print('PASS: split, vertical split, tab, preview reuse, and drop placement')
  vim.cmd('Jedit file.lua')
  local old = file.buffer_content(0)
  local head = file.resolve(root, '@')
  -- Force an undo boundary between scripted commands.
  vim.cmd('let &undolevels = &undolevels')
  vim.cmd('Jread -r ' .. base)
  eq('one\ntwo\nthree\n', file.buffer_content(0)); eq(true, vim.bo.modified)
  eq(head, file.resolve(root, '@'))
  vim.cmd.undo(); eq(old, file.buffer_content(0))
  vim.cmd('0Jread -r ' .. base)
  eq('one', vim.api.nvim_buf_get_lines(0, 0, 1, false)[1])
  local length = vim.api.nvim_buf_line_count(0)
  vim.cmd('2,3Jread -r ' .. base)
  eq(length + 1, vim.api.nvim_buf_line_count(0))
  vim.cmd('%Jread -r ' .. base)
  eq('one\ntwo\nthree\n', file.buffer_content(0))
  vim.bo.modifiable = false
  eq(false, pcall(vim.cmd, 'Jread')); vim.bo.modifiable = true
  print('PASS: Jread restoration, insertion, ranged replacement, undo, and repository isolation')
  vim.bo.modified = false
  vim.api.nvim_set_current_buf(buf)
  log.refresh(buf)
  vim.api.nvim_win_set_cursor(0, { find(function(r) return not r.path and r.working_copy end), 0 })
  log.visit(buf)
  eq(true, vim.b.fujutsu_file.description); eq(false, vim.bo.readonly)
  local description = vim.api.nvim_get_current_buf()
  vim.api.nvim_buf_set_lines(0, 0, -1, false, { 'new description' })
  vim.cmd.write()
  eq('new description\n', jj({ 'log', '--no-graph', '-r', '@', '-T', 'description' }))
  eq(false, vim.bo.modified)
  jj({ 'describe', '-m', 'external description' })
  vim.api.nvim_buf_set_lines(0, 0, -1, false, { 'my description' })
  eq(false, pcall(file.write, description, {})); eq(true, vim.bo.modified)
  vim.cmd('Jwrite!')
  eq('my description\n', jj({ 'log', '--no-graph', '-r', '@', '-T', 'description' }))
  vim.bo.readonly = true
  eq(false, pcall(file.write, description, {}))
  eq(false, pcall(file.write, description, { bang = true, restore_descendants = true }))
  jj({ 'config', 'set', '--repo', 'revset-aliases."immutable_heads()"', '@' })
  vim.api.nvim_buf_set_lines(0, 0, -1, false, { 'immutable edit' })
  eq(false, pcall(file.write, description, { bang = true })); eq(true, vim.bo.modified)
  vim.cmd('Jwrite! --ignore-immutable')
  eq(false, vim.bo.modified)
  jj({ 'config', 'set', '--repo', 'revset-aliases."immutable_heads()"', 'root()' })
  print('PASS: description navigation, writes, stale replacement, readonly, immutability, and failure retention')
  vim.api.nvim_set_current_buf(buf)
  log.refresh(buf)
  vim.api.nvim_win_set_cursor(0, { 1, 0 })
  log.move('revision', 1, 2)
  local revision = vim.fn.line('.')
  eq(revision, (log.rows[revision].entry or log.rows[revision]).first)
  local first_revision = find(function(r) return r.id ~= nil end)
  log.move('revision', -1, 999); eq(first_revision, vim.fn.line('.'))
  log.move('revision', -1, 1); eq(first_revision, vim.fn.line('.'))
  vim.api.nvim_win_set_cursor(0, { find(function(r) return r.path == 'file.lua' end), 0 })
  -- Expand a file if necessary; movement itself never changes expansion.
  local has_hunk = false
  for _, row in pairs(log.rows) do if row.hunk then has_hunk = true end end
  if not has_hunk then log.toggle(buf) end
  vim.api.nvim_win_set_cursor(0, { 1, 0 }); log.move('hunk', 1, 1)
  assert(log.rows[vim.fn.line('.')].hunk)
  log.move('file', -1, 1)
  eq(vim.fn.line('.'), log.rows[vim.fn.line('.')].first)
  log.toggle(buf) -- Collapse; hidden hunks must no longer be destinations.
  vim.api.nvim_win_set_cursor(0, { 1, 0 }); log.move('hunk', 1, 999)
  eq(1, vim.fn.line('.'))
  log.move('file', 1, 999)
  local last = vim.fn.line('.'); log.move('file', 1, 1); eq(last, vim.fn.line('.'))
  print('PASS: boundary motion counts, backward movement, collapsed hunks, and buffer limits')
  vim.cmd('Jedit file.lua')
  vim.cmd.J()
  local logbuf = vim.api.nvim_get_current_buf()
  local parent = vim.fn.maparg('-', 'n', false, true)
  eq(1, parent.buffer)
  parent.callback()
  eq(root .. '/.jj', vim.api.nvim_buf_get_name(0):gsub('/$', ''))
  eq(true, vim.fn.isdirectory(vim.api.nvim_buf_get_name(0)) == 1)
  eq(true, vim.api.nvim_buf_is_valid(logbuf)) -- Keep jump-list destinations alive.
  eq(false, vim.api.nvim_buf_is_loaded(logbuf))
  eq(false, vim.bo[logbuf].buflisted)
  print('PASS: log parent navigation opens this repository metadata directory')
end
local ok, err = xpcall(test, debug.traceback)
vim.fn.delete(root, 'rf')
if not ok then io.stderr:write(err .. '\n'); vim.cmd.cquit(1) end
vim.cmd('qa!')
