vim.opt.runtimepath:prepend(vim.fn.getcwd())
vim.cmd.runtime('plugin/fujutsu.lua')
local file = require('fujutsu.file')
local root = vim.fn.tempname()
vim.fn.mkdir(root, 'p')
local function jj(args) return file.jj(root, args) end
local function eq(a, b) assert(vim.deep_equal(a, b), vim.inspect({ expected = a, actual = b })) end
local function test()
  jj({ 'git', 'init' })
  vim.fn.writefile({ 'one', 'two', 'three' }, root .. '/file.lua')
  jj({ 'describe', '-m', 'base' })
  local base = file.resolve(root, '@')
  jj({ 'new' })
  vim.fn.writefile({ 'one', 'changed', 'three' }, root .. '/file.lua')
  local current = file.resolve(root, '@')
  eq('one\ntwo\nthree\n', file.base(root, current, 'file.lua'))
  file.open(root, base, 'file.lua')
  eq(true, vim.bo.readonly); eq(true, vim.bo.modifiable); eq('lua', vim.bo.filetype)
  eq(base, vim.b.fujutsu_file.id)
  file.open(root, current, 'file.lua', { workspace = true })
  local workspace = vim.api.nvim_get_current_buf()
  file.open(root, current, 'file.lua', { workspace = true })
  eq(workspace, vim.api.nvim_get_current_buf())
  local log = require('fujutsu.log').new(root, file.jj)
  local buf = vim.api.nvim_create_buf(false, true)
  vim.api.nvim_set_current_buf(buf)
  log.refresh(buf)
  local function find(predicate)
    for i, row in pairs(log.rows) do if predicate(row) then return i end end
    error('row not found')
  end
  vim.api.nvim_win_set_cursor(0, { find(function(r) return r.path == 'file.lua' end), 0 })
  log.toggle(buf)
  local removed = find(function(r) return r.old_side end)
  vim.api.nvim_win_set_cursor(0, { removed, 0 }); log.visit(buf)
  eq(base, vim.b.fujutsu_file.id); eq(2, vim.fn.line('.'))
  vim.api.nvim_set_current_buf(buf)
  vim.api.nvim_win_set_cursor(0, { find(function(r) return r.new_line == 2 and not r.old_side and not r.hunk end), 0 })
  log.visit(buf); eq(workspace, vim.api.nvim_get_current_buf()); eq(2, vim.fn.line('.'))
  print('PASS: revision snapshots, merged-base extraction, workspace reuse, and diff coordinates')
end
local ok, err = xpcall(test, debug.traceback)
vim.fn.delete(root, 'rf')
if not ok then io.stderr:write(err .. '\n'); vim.cmd.cquit(1) end
vim.cmd('qa!')
