vim.opt.runtimepath:prepend(vim.fn.getcwd())
vim.cmd.runtime('plugin/fujutsu.lua')
local tmp = vim.fn.tempname()
local function run(args)
  local result = vim.system(vim.list_extend({ 'jj', '--no-pager', '--color=never' }, args), { cwd = tmp, text = true }):wait()
  assert(result.code == 0, result.stderr)
  return vim.trim(result.stdout)
end
vim.fn.mkdir(tmp, 'p')
run({ 'git', 'init' })
run({ 'config', 'set', '--repo', 'user.name', 'Test' })
run({ 'config', 'set', '--repo', 'user.email', 'test@example.com' })
run({ 'describe', '-m', 'source' })
vim.fn.writefile({ 'hello' }, tmp .. '/file')
local id = run({ 'log', '--no-graph', '-r', '@', '-T', 'change_id' })
vim.cmd.cd(tmp)
vim.cmd.J()
local buf = vim.api.nvim_get_current_buf()
local function keys(text)
  vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes(text, true, false, true), 'xt', false)
end
local function find(text)
  for i, line in ipairs(vim.api.nvim_buf_get_lines(buf, 0, -1, false)) do
    if line:find(text, 1, true) then vim.api.nvim_win_set_cursor(0, { i, 0 }); return i end
  end
  error('Missing row: ' .. text)
end
find('source'); keys('m')
assert(vim.fn.getreg('"') == 'change_id(' .. id .. ')')
find('source'); keys('"am')
find('source'); keys('"aM')
assert(#require('fujutsu.marks').parse(vim.fn.getreg('a')) == 1)
find('  a'); keys('<Space>')
assert(#vim.api.nvim_buf_get_extmarks(buf, vim.api.nvim_create_namespace('fujutsu.marks'), 0, -1, {}) >= 2)
find('source'); keys('"ad')
assert(vim.fn.getreg('a') == '')
find('source'); keys('yy')
assert(not require('fujutsu.marks').parse(vim.fn.getreg('"')))
vim.wait(50, function() return false end)
print('PASS: log mark mappings, pinning, removal and ordinary yanking')
vim.cmd.cd('/')
vim.fn.delete(tmp, 'rf')
vim.cmd.qa({ bang = true })
