vim.opt.runtimepath:prepend(vim.fn.getcwd())
local marks = require('fujutsu.marks')
local a, b = string.rep('k', 32), string.rep('z', 32)
local function eq(a_, b_) assert(vim.deep_equal(a_, b_), vim.inspect({ a_, b_ })) end
marks.modify('a', 'replace', { a })
eq({ a }, marks.parse(vim.fn.getreg('"')))
marks.modify('A', 'replace', { a, b })
eq({ a, b }, marks.parse(vim.fn.getreg('a')))
marks.modify('a', 'remove', { a })
eq({ b }, marks.parse(vim.fn.getreg('a')))
eq({ a, b }, marks.parse(vim.fn.getreg('"')))
marks.modify('"', 'remove', { b })
eq({ a }, marks.parse(vim.fn.getreg('"')))
eq(nil, marks.parse('ordinary yank'))
eq(nil, marks.get('a', { [b] = false }))
eq(nil, marks.get('a', {}))
local ids, commits = marks.get('a', { [b] = 'abc' })
eq({ b }, ids); eq({ 'abc' }, commits)
vim.fn.setreg('"', 'copied text')
eq(nil, marks.get('"', { [a] = 'def' }))
print('PASS: native register selection union, subtraction, unnamed alias and validation')
vim.cmd.qa({ bang = true })
