vim.opt.runtimepath:prepend(vim.fn.getcwd())
vim.cmd.runtime('plugin/fujutsu.lua')
vim.o.hidden = true
local file = require('fujutsu.file')
local tmp = vim.fn.tempname()
vim.fn.mkdir(tmp, 'p')
tmp = vim.uv.fs_realpath(tmp)
local function eq(a, b) assert(vim.deep_equal(a, b), vim.inspect({ expected = a, actual = b })) end
local function repo(name)
  local root = tmp .. '/' .. name
  vim.fn.mkdir(root, 'p')
  file.jj(root, { 'git', 'init' })
  return root, function(args) return file.jj(root, args) end
end
local function test()
  local root, jj = repo('merge')
  vim.fn.writefile({ 'one', 'two', 'three' }, root .. '/file.txt')
  local base = file.resolve(root, '@')
  jj({ 'new', base })
  vim.fn.writefile({ 'ONE', 'two', 'three' }, root .. '/file.txt')
  local left = file.resolve(root, '@')
  jj({ 'new', base })
  vim.fn.writefile({ 'one', 'two', 'THREE' }, root .. '/file.txt')
  local right = file.resolve(root, '@')
  jj({ 'new', left, right })
  vim.fn.writefile({ 'ONE', 'changed', 'THREE' }, root .. '/file.txt')
  local merge = file.resolve(root, '@')
  eq('ONE\ntwo\nTHREE\n', file.base(root, merge, 'file.txt'))
  local log = require('fujutsu.log').new(root, file.jj)
  local buf = vim.api.nvim_create_buf(false, true)
  vim.api.nvim_set_current_buf(buf); log.refresh(buf)
  local function find(predicate)
    for index, row in pairs(log.rows) do if predicate(row) then return index end end
    error('Missing row')
  end
  vim.api.nvim_win_set_cursor(0, { find(function(r) return r.path == 'file.txt' end), 0 })
  log.toggle(buf)
  vim.api.nvim_win_set_cursor(0, { find(function(r) return r.old_side end), 0 }); log.visit(buf)
  eq(true, vim.b.fujutsu_file.base); eq('ONE\ntwo\nTHREE\n', file.buffer_content(0))
  eq(false, pcall(file.write, vim.api.nvim_get_current_buf(), { bang = true }))
  require('fujutsu.tree').parent(1)
  eq(true, vim.b.fujutsu_tree.base)
  eq({ 'file.txt' }, vim.api.nvim_buf_get_lines(0, 0, -1, false))
  vim.fn.maparg('<CR>', 'n', false, true).callback()
  eq(true, vim.b.fujutsu_file.base)
  eq('ONE\ntwo\nTHREE\n', file.buffer_content(0))
  vim.api.nvim_set_current_buf(buf)
  vim.api.nvim_win_set_cursor(0, { find(function(r) return r.new_line == 2 and not r.old_side end), 0 })
  vim.fn.writefile({ 'new', 'ONE', 'changed', 'THREE' }, root .. '/file.txt')
  eq(false, pcall(log.visit, buf))
  print('PASS: real merged-parent navigation, synthetic write refusal, and stale coordinates')

  root, jj = repo('writes')
  vim.fn.writefile({ 'base' }, root .. '/file.txt')
  vim.fn.writefile({ 'unrelated' }, root .. '/other.txt')
  base = file.resolve(root, '@')
  jj({ 'new' })
  local _, wc_change = file.resolve(root, '@')
  file.open(root, base, 'file.txt')
  local historical = vim.api.nvim_get_current_buf()
  vim.api.nvim_buf_set_lines(0, 0, -1, false, { 'ordinary rebase' })
  vim.cmd('write!')
  eq(false, vim.bo.modified); eq(true, vim.bo.readonly)
  eq('ordinary rebase\n', file.content(root, '@', 'file.txt'))
  eq('unrelated\n', file.content(root, '@-', 'other.txt'))
  local _, after_change = file.resolve(root, '@'); eq(wc_change, after_change)
  local saved = vim.b.fujutsu_file.id
  file.open(root, base, 'file.txt')
  local pinned = vim.api.nvim_get_current_buf()
  eq('base\n', file.buffer_content(0))
  vim.api.nvim_set_current_buf(historical)
  vim.api.nvim_buf_set_lines(0, 0, -1, false, { 'again' })
  vim.cmd('Jwrite! --restore-descendants')
  eq(base, vim.b[pinned].fujutsu_file.id)
  eq('ordinary rebase\n', file.content(root, '@', 'file.txt'))
  jj({ 'abandon', vim.b.fujutsu_file.id })
  eq(false, pcall(file.write, historical, { bang = true }))
  file.open(root, vim.b.fujutsu_file.id, 'file.txt', { explicit = true })
  vim.api.nvim_buf_set_lines(0, 0, -1, false, { 'explicit resurrection' })
  vim.cmd('Jwrite!')
  eq(false, vim.bo.modified)
  print('PASS: write bang, normal descendant rebasing, unrelated files, snapshot pinning, and abandonment')

  root, jj = repo('divergence')
  vim.fn.writefile({ 'base' }, root .. '/file.txt')
  base = file.resolve(root, '@')
  jj({ 'new' })
  file.open(root, base, 'file.txt')
  historical = vim.api.nvim_get_current_buf()
  local op = vim.trim(jj({ 'op', 'log', '--no-graph', '-n', '1', '-T', 'id' }))
  jj({ 'describe', '-r', base, '-m', 'first' })
  jj({ '--at-op', op, 'describe', '-r', base, '-m', 'second' })
  jj({ 'log' }) -- Integrate the concurrent operations.
  eq(false, pcall(file.write, historical, { bang = true }))
  local candidates = jj({ 'log', '--no-graph', '-r', 'change_id(' .. vim.b.fujutsu_file.change .. ')', '-T', 'commit_id ++ "\\n"' })
  local selected = candidates:match('^(%x+)')
  file.open(root, selected, 'file.txt', { explicit = true })
  vim.api.nvim_buf_set_lines(0, 0, -1, false, { 'explicit branch edit' })
  vim.cmd('Jwrite!')
  eq(false, vim.bo.modified)
  eq('explicit branch edit\n', file.content(root, vim.b.fujutsu_file.id, 'file.txt'))
  print('PASS: divergent and abandoned changes require explicit reselection, not just bang')

  root, jj = repo('race')
  vim.fn.writefile({ 'base' }, root .. '/file.txt')
  base = file.resolve(root, '@')
  jj({ 'new' })
  file.open(root, base, 'file.txt')
  historical = vim.api.nvim_get_current_buf()
  vim.api.nvim_buf_set_lines(0, 0, -1, false, { 'pending' })
  local original = file.jj
  file.jj = function(cwd, args)
    if vim.tbl_contains(args, 'diffedit') then
      original(cwd, { 'describe', '-r', base, '-m', 'concurrent update' })
    end
    return original(cwd, args)
  end
  local ok = pcall(file.write, historical, { bang = true })
  file.jj = original
  eq(false, ok); eq(true, vim.bo.modified)
  eq('base\n', file.content(root, '@-', 'file.txt'))
  eq('pending\n', file.buffer_content(0))
  print('PASS: editor-time revalidation refuses a concurrent rewrite and retains edits')
end
local ok, err = xpcall(test, debug.traceback)
vim.fn.delete(tmp, 'rf')
if not ok then io.stderr:write(err .. '\n'); vim.cmd.cquit(1) end
vim.cmd('qa!')
